services:
  - type: web
    name: dormitory-management-system
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: dormitory-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dormitory-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: dormitory-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dormitory-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dormitory-db
          property: password

databases:
  - name: dormitory-db
    databaseName: dormitory
    user: dormitory
    plan: free
